FROM nginx:latest
RUN apt-get update  

# RUN apk update && apk add vim && apk add tree && apk add openrc
# openrcはsystemctlと同じ意味のコマンド
# systemctl status系のコマンド
# rc-status
# rc-service nginx checkconfig
# Checking nginx configuration ... という記載があれば問題なし