# version: '3'

# services:
#   nginx:
#     container_name: nginx_test
#     build: ./nginx
#     ports:
#       - "8080:80"
#     volumes:
#       - ./src:/var/www/html
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

#   php:
#     container_name: php_test
#     build: ./php
#     volumes:
#       - ./src:/var/www/html



version: "3.7"
services:
  # セクション名については任意の名前で構わない。
  web:
    # Dockerイメージを指定
    build: ./nginx
    ports:
      # プロキシサーバのポートを指定（ホスト側:コンテナ側）
      - "8080:80"
    volumes:
      # nginxのconfigファイルをマウントしdefault.confへ上書き
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    # Dockerイメージを指定、PHPバージョンは7.3
    image: php:7-fpm
    # FastCGIサーバのデフォルトポートを使用するためports指定なし
    volumes:
      # 実行対象のPHPファイルをマウント
      - ./src/:/var/phpapp/